### ISSUE TITLE
misuse of font

### ISSUE THREAD

**Issue by Level237** [maelfosso/kipart-ui-design#1]

**Comment by Level237** [comment]
1. ### Affected page

- every page

2. ### Description

- the fonts are not the same

3-Loom video

- links of original design: https://www.loom.com/share/7b4d48d4d98f45b48ea7376c99c5329f
- links of your template create: https://www.loom.com/share/20f38135b20f4368ad9fe69d1c898b65

**Comment by maelfosso** [comment]
I just added the font.
Can you test it again ?

**Comment by Level237** [comment]
- @maelfosso ok wait please

**Comment by maelfosso** [comment]
@Level237 have you checked it, please?
If so, kindly close the issue if it's Okay

**Comment by Level237** [comment]
-yes it's ok I close the issue
