### ISSUE TITLE
 page conflict

### ISSUE THREAD

**Issue by Level237** [maelfosso/kipart-ui-design#3]
1-**concerned page**

- page index and login

2-**Description**

- the index and login pages must be separated

3- loom video

https://www.loom.com/share/4d214ac65f894eca9a31f306b163ef99

**Comment by maelfosso** [comment]
Sorry but from the design login and register are modal/dialog
I implemented them as such. 

Please, take a look at this video
https://www.loom.com/share/642880bec6ac4905a55a4513f670180d

**Comment by Level237** [comment]
@maelfosso -ok it's good
